# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each day, while testing, will change to weekly later)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:                                 #!!##############!!#
          token: ${{ secrets.METRICS_TOKEN }} # EXPIRES 1/1/2025 #
          # General options                   #!!##############!!#
          user: TomJo2000
          template: classic
          base: header, calendar, community, repositories, metadata
          config_timezone: Europe/Berlin
          # Order of content
          config_order: notable, lines, languages, activity, followup, discussions
          # Activity
          plugin_calendar: yes
          # Discissions
          plugin_discussions: yes
          plugin_discussions_categories: yes
          # Follow-up
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          # Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          # Lines
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          # Notable contributions
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          # Traffic
          plugin_traffic: yes
